server:
  port: 8081

spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://ep-weathered-math-909876.us-east-2.aws.neon.tech/credit_conveyor
    username: ssoslickk
    password: H94xCKgdQjuS

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.sunshard.deal.serializer.EmailMessageSerializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: SsoslickK@gmail.com
    password: peqidhtqtxbmuvmr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

conveyor-address: localhost:8080