server:
  port: 8082

spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://ep-weathered-math-909876.us-east-2.aws.neon.tech/credit_conveyor
    username: ssoslickk
    password: H94xCKgdQjuS

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

conveyor-address: localhost:8081