server:
  port: 8082

conveyor-address: localhost:8081

spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/cc_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
