spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: SsoslickK@gmail.com
    password: peqidhtqtxbmuvmr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true